# Generated by Django 5.0.6 on 2024-07-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="full_name",
            new_name="fullName",
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
