# Generated by Django 5.0.6 on 2024-07-27 13:12

import django.db.models.deletion
import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0002_rename_full_name_profile_fullname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=myauth.models.avatar_directory_path,
                    ),
                ),
                ("img", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to="myauth.avatarimage",
            ),
            preserve_default=False,
        ),
    ]
