# Generated by Django 5.0.6 on 2024-07-27 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0003_avatarimage_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to="myauth.avatarimage",
            ),
        ),
    ]
