# Generated by Django 5.0.6 on 2024-07-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0004_alter_profile_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avatarimage",
            old_name="img",
            new_name="alt",
        ),
    ]
