# Generated by Django 5.0.6 on 2024-07-27 15:31

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0005_rename_img_avatarimage_alt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="profile",
            name="alt",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="src",
            field=models.ImageField(
                blank=True, null=True, upload_to=myauth.models.avatar_directory_path
            ),
        ),
        migrations.DeleteModel(
            name="AvatarImage",
        ),
    ]
