# Generated by Django 5.0.6 on 2024-07-25 14:53

import django.core.validators
import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True, db_index=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shopapp.models.product_preview_directory_path,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "price"],
            },
        ),
    ]
