# Generated by Django 5.0.6 on 2024-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="shopapp.tag"
            ),
        ),
    ]
