# Generated by Django 5.0.6 on 2024-08-07 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0006_remove_profile_avatar_profile_alt_profile_src_and_more"),
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_profile",
                to="myauth.profile",
            ),
        ),
    ]
