# Generated by Django 5.0.6 on 2024-08-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0002_alter_order_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
