# Generated by Django 5.0.6 on 2024-08-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0003_alter_order_deliverytype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True, default="processing", max_length=20, null=True
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=8)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("month", models.CharField(blank=True, max_length=2)),
                ("year", models.CharField(blank=True, max_length=4)),
                ("code", models.CharField(blank=True, max_length=3)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="shopapp.order",
                    ),
                ),
            ],
        ),
    ]
