# Generated by Django 5.0.6 on 2024-08-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_alter_productimage_product_alter_review_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="images",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="shopapp.productimage",
            ),
            preserve_default=False,
        ),
    ]
