# Generated by Django 5.0.6 on 2024-08-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_product_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                auto_created=True, blank=True, decimal_places=2, default=0, max_digits=3
            ),
        ),
    ]
